@TodoApi_HostAddress = https://localhost:7221

# defines a POST request.
Post {{TodoApi_HostAddress}}/todoitems
Content-Type: application/json

{
  "name":"walk dog",
  "isComplete":true
}

###
GET {{TodoApi_HostAddress}}/todoitems/1
###
GET {{TodoApi_HostAddress}}/todoitems

###
@id=0
DELETE {{TodoApi_HostAddress}}/todoitems/{{id}}

###
